import { Button } from '@mui/material';
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import styles from '../styles/Home.module.css';
import { Box } from '@mui/system';
import { TwitterTweetEmbed } from 'react-twitter-embed';
import { rankTweets } from '../libs/utiliities';

export default function Home({ tweets, trends }) {

  return (
    <div className={styles.container}>
      <Head>
        <title>Twitter Flame</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <h1>Web Scraping in Nextjs</h1>
      <Link href='/api/trends'>
        <Button variant='contained'>Go to api</Button>
      </Link>

      <pre></pre>
      <pre>
        {JSON.stringify(trends, undefined, 4)}
        {JSON.stringify(rankTweets(tweets), undefined, 4)}
        {tweets.map((t) => (
          <div key={t.id}>
            <TwitterTweetEmbed tweetId={t.id} options={{ cards: 'hidden' }} />
            <p>{t.fav + ' -  ' + ' R ' + t.retweet + ' - Q ' + t.quote}</p>
          </div>
        ))}
      </pre>
    </div>
  );
}

export async function getStaticProps() {


  
  const tweetsResponse = await fetch('http://localhost:3000/api/all')
  const tweetsJson = await tweetsResponse.json()
  const tweets =tweetsJson.results[0].tweets
  const trends = tweetsJson.results.map(r => `${r.name} - ${r.trendScore}`)
  return {
    props: { tweets, trends },
  };
}
